// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvXs6H1mnpftmF3YKqtPTwDr6kRdezP9E',
    appId: '1:60561028816:web:d6570d3c51a30b354c10d5',
    messagingSenderId: '60561028816',
    projectId: 'ecommerceapp-a1c6c',
    authDomain: 'ecommerceapp-a1c6c.firebaseapp.com',
    storageBucket: 'ecommerceapp-a1c6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnr8D_PM-grf6rjIRlpduekoeehxKITJ4',
    appId: '1:60561028816:android:f27dd640725cc2634c10d5',
    messagingSenderId: '60561028816',
    projectId: 'ecommerceapp-a1c6c',
    storageBucket: 'ecommerceapp-a1c6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBODiTIJKr9yQHcSUXy4ZrwqFrdI9CDh7I',
    appId: '1:60561028816:ios:cd6a392a8358546f4c10d5',
    messagingSenderId: '60561028816',
    projectId: 'ecommerceapp-a1c6c',
    storageBucket: 'ecommerceapp-a1c6c.appspot.com',
    androidClientId: '60561028816-pt80bfmpjvj085d5s5j3onmj624n7jv9.apps.googleusercontent.com',
    iosClientId: '60561028816-4olbartf3190smt6bfstn79ah98b1me0.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBODiTIJKr9yQHcSUXy4ZrwqFrdI9CDh7I',
    appId: '1:60561028816:ios:27c8fc58062d31c74c10d5',
    messagingSenderId: '60561028816',
    projectId: 'ecommerceapp-a1c6c',
    storageBucket: 'ecommerceapp-a1c6c.appspot.com',
    androidClientId: '60561028816-pt80bfmpjvj085d5s5j3onmj624n7jv9.apps.googleusercontent.com',
    iosClientId: '60561028816-refcd6daci0spugppgkgt0kvhp8kenkk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
